---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci"
    schedule:
      interval: "daily"
